### ISSUE TITLE
More wheels for Python 3.12

### ISSUE THREAD

**Issue by tvuotila** [jams2/py-svg-hush#1]
We are upgrading from Python 3.11 to 3.12 and noticed that installing py-svg-hush started to fail because of missing Rust build tools. Py-svg-hush provides wheels for 10 different Python 3.11 environments, but only 3 different Python 3.12 environments.

Would it be possible to upload more wheels to PyPI?

**Comment by jams2** [comment]
Hi @tvuotila , I have released 0.1.2 which contains wheels for many different targets: https://pypi.org/project/py-svg-hush/#files. Does this fit your use-case?

**Comment by tvuotila** [comment]
Yes, these wheels fit my use case. Thank you.

**Comment by jams2** [comment]
Thanks for opening issue number 1 @tvuotila . If you can share, I would be happy to hear what you're using this package for.

**Comment by tvuotila** [comment]
It is not a secret where I work; it is mentioned in my GitHub profile. We have a product called [Falcony](https://falcony.io). We use py-svg-hush to sanitize some of the button icons we use in the application, specifically those that don't come from some premade icon library.
